# Generated by Django 5.2.1 on 2025-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen Reporter'), ('moderator', 'Platform Moderator'), ('manager', 'Municipal Manager')], default='citizen', max_length=20),
        ),
    ]
