# Generated by Django 5.2.1 on 2025-05-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes for administrators only.', null=True),
        ),
    ]
