# Generated by Django 5.2.1 on 2025-05-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_internal_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-priority', '-reported_date']},
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to_manager',
            field=models.ForeignKey(blank=True, help_text='Municipal Manager currently responsible for this issue', limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low Priority'), ('Medium', 'Medium Priority'), ('High', 'High Priority')], default='Medium', help_text='Priority level of the issue (Low, Medium, High)', max_length=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_image',
            field=models.ImageField(blank=True, help_text='Optional image uploaded by the manager showing the resolved issue or work done', null=True, upload_to='resolution_images/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Detailed notes from the manager about the resolution or actions taken', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes for administrators/moderators only.', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Under Review', 'Under Review'), ('Verified', 'Verified & Awaiting Assignment'), ('Assigned', 'Assigned to Manager'), ('Manager Acknowledged', 'Manager: Acknowledged'), ('Manager Investigating', 'Manager: Investigating'), ('Work In Progress', 'Manager: Work In Progress'), ('Awaiting Resources', 'Manager: Awaiting Resources'), ('Requires Assistance', 'Manager: Requires Moderator Assistance'), ('Action Taken', 'Action Taken'), ('Resolved', 'Resolved'), ('Closed-No Action', 'Closed-No Action'), ('Duplicate', 'Duplicate Issue'), ('Invalid', 'Invalid Report')], default='Reported', max_length=50),
        ),
    ]
