# Generated by Django 5.2.1 on 2025-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_options_issue_assigned_to_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='municipal_area',
            field=models.CharField(blank=True, help_text='Automatically determined municipal area/ward/suburb from location', max_length=255, null=True),
        ),
    ]
